main: Fludixx\Skywars\Skywars
api: 
- 3.0.0
- 4.0.0
name: SkyWars
author: Fludixx
depend: ['Sagiri-API']
description: SkyWars
version: 1
commands:
  sw:
    description: "Skywars Command"
  swsign:
    description: "Skywars Sign Command"
  stats:
      description: "Skywars Stats"
  swupdate:
      description: "Start SignUpdater"
permissions:
  sw.start:
    default: op
    description: "Establecer El Timpo De Inicio A 10s"
